project:
  type: website

website:
  title: "Text Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: _static/styles.css
    toc: true



