project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!scripts/"

execute: 
  enabled: false
  freeze: auto
  cache: true

website:
  title: "Introduction to Text Analysis in R"
  search:
    location: navbar
  navbar:
    tools:
      - text: "About RDS"
        href: about.qmd
      - icon: github
        menu:
          - text: "Source Code"
            url: https://github.com/UCSB-Library-Research-Data-Services/text-analysis-series
            target: _blank
          - text: "Report a Bug"
            url: https://github.com/UCSB-Library-Research-Data-Services/text-analysis-series/issues/new?title=Bug%20Report%3A%20%5BDescribe%20the%20issue%20briefly%5D&body=**Description%20of%20the%20issue%3A**%0A%0A**Steps%20to%20reproduce%3A**%0A1.%20%0A2.%20%0A3.%20%0A%0A**Expected%20behavior%3A**%0A%0A**Actual%20behavior%3A**%0A%0A**Additional%20context%3A**
            target: _blank
  sidebar:
    style: docked
    border: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: chapters/1.Preprocessing/01_introduction.qmd
        text: Introduction to Text Preprocessing
      - href: chapters/1.Preprocessing/02_normalization.qmd
        text: Normalization & Noise Reduction
      - href: chapters/1.Preprocessing/03_tokenization.qmd
        text: Word Tokenization
      - href: chapters/1.Preprocessing/04_stopwords.qmd
        text: Stop Words Removal
      - href: chapters/1.Preprocessing/05_lemmatization.qmd
        text: Lemmatization
      - href: chapters/1.Preprocessing/06_conclusion.qmd
        text: Conclusion
      #- href: chapters/2.TextAnalysis/introduction.qmd
        #text: Text Analysis
      #- href: chapters/3.SentimentAnalysis/introduction.qmd
        #text: Sentiment Analysis
      - about.qmd

  page-footer:
    background: "#003660" # UCSB blue
    center: >
      This website is built with [Quarto](https://quarto.org/), [RStudio/Posit](https://posit.co/),
      and [webexercises R package](https://cran.r-project.org/web/packages/webexercises/index.html).
      UCSB Library Research Data Services. [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en)
    left: |
      <img src="_static/images/RDS-logo.png" alt="UCSB Library Research Data Services logo" width="250"/>


format:
  html:
    css: _static/adapt-meds-website-styles.scss
    toc: true
    page-layout: full
    code-line-numbers: false
    code-fold: false
    code-tools: true



